name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Attach bundle to release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload dist file to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/f1-dashboard-card.js
